/*
 * generated by Xtext 2.32.0
 */
package org.feup.els5.dsl.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.feup.els5.dsl.parser.antlr.internal.InternalTableDSLParser;
import org.feup.els5.dsl.services.TableDSLGrammarAccess;

public class TableDSLParser extends AbstractAntlrParser {

	@Inject
	private TableDSLGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalTableDSLParser createParser(XtextTokenStream stream) {
		return new InternalTableDSLParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Start";
	}

	public TableDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TableDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
