/*
 * generated by Xtext 2.32.0
 */
package org.feup.els5.dsl.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.feup.els5.dsl.ide.contentassist.antlr.internal.InternalTableDSLParser;
import org.feup.els5.dsl.services.TableDSLGrammarAccess;

public class TableDSLParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(TableDSLGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, TableDSLGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getTableActionAccess().getAlternatives(), "rule__TableAction__Alternatives");
			builder.put(grammarAccess.getOperationAccess().getAlternatives(), "rule__Operation__Alternatives");
			builder.put(grammarAccess.getStartAccess().getGroup(), "rule__Start__Group__0");
			builder.put(grammarAccess.getCreateTableAccess().getGroup(), "rule__CreateTable__Group__0");
			builder.put(grammarAccess.getTableActionAccess().getGroup_2(), "rule__TableAction__Group_2__0");
			builder.put(grammarAccess.getLoadDataAccess().getGroup(), "rule__LoadData__Group__0");
			builder.put(grammarAccess.getOutputAccess().getGroup(), "rule__Output__Group__0");
			builder.put(grammarAccess.getSelectAccess().getGroup(), "rule__Select__Group__0");
			builder.put(grammarAccess.getRenameColumnAccess().getGroup(), "rule__RenameColumn__Group__0");
			builder.put(grammarAccess.getExtractAccess().getGroup(), "rule__Extract__Group__0");
			builder.put(grammarAccess.getSquashRowsAccess().getGroup(), "rule__SquashRows__Group__0");
			builder.put(grammarAccess.getFilterAccess().getGroup(), "rule__Filter__Group__0");
			builder.put(grammarAccess.getStartAccess().getActionsAssignment_0(), "rule__Start__ActionsAssignment_0");
			builder.put(grammarAccess.getStartAccess().getActionsAssignment_1(), "rule__Start__ActionsAssignment_1");
			builder.put(grammarAccess.getTableInputPathAccess().getPathPatternsAssignment(), "rule__TableInputPath__PathPatternsAssignment");
			builder.put(grammarAccess.getOutputAccess().getOutputPathAssignment_2(), "rule__Output__OutputPathAssignment_2");
			builder.put(grammarAccess.getSelectAccess().getColumnsAssignment_1(), "rule__Select__ColumnsAssignment_1");
			builder.put(grammarAccess.getRenameColumnAccess().getOldNameAssignment_1(), "rule__RenameColumn__OldNameAssignment_1");
			builder.put(grammarAccess.getRenameColumnAccess().getNewNameAssignment_3(), "rule__RenameColumn__NewNameAssignment_3");
			builder.put(grammarAccess.getExtractAccess().getPlaceholderAssignment_1(), "rule__Extract__PlaceholderAssignment_1");
			builder.put(grammarAccess.getSquashRowsAccess().getColumnAssignment_3(), "rule__SquashRows__ColumnAssignment_3");
			builder.put(grammarAccess.getFilterAccess().getPlaceholderAssignment_2(), "rule__Filter__PlaceholderAssignment_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private TableDSLGrammarAccess grammarAccess;

	@Override
	protected InternalTableDSLParser createParser() {
		InternalTableDSLParser result = new InternalTableDSLParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public TableDSLGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(TableDSLGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
