/*
 * generated by Xtext 2.33.0
 */
package org.feup.els5.dsl.validation;

import java.util.ArrayList;
import java.util.List;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.xtext.validation.AbstractDeclarativeValidator;

public abstract class AbstractTableDSLValidator extends AbstractDeclarativeValidator {
	
	@Override
	protected List<EPackage> getEPackages() {
		List<EPackage> result = new ArrayList<EPackage>();
		result.add(org.feup.els5.dsl.tableDSL.TableDSLPackage.eINSTANCE);
		return result;
	}
}
