/*
 * generated by Xtext 2.32.0
 */
package org.feup.els5.dsl.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractTableDSLScopeProvider extends DelegatingScopeProvider {
}
