/**
 * generated by Xtext 2.32.0
 */
package org.feup.els5.dsl.tableDSL.impl;

import org.eclipse.emf.common.notify.Notification;

import org.eclipse.emf.ecore.EClass;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.feup.els5.dsl.tableDSL.FilterObjectTypeRule;
import org.feup.els5.dsl.tableDSL.TableDSLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Filter Object Type Rule</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.feup.els5.dsl.tableDSL.impl.FilterObjectTypeRuleImpl#getColumnPattern <em>Column Pattern</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FilterObjectTypeRuleImpl extends FilterRuleImpl implements FilterObjectTypeRule
{
  /**
   * The default value of the '{@link #getColumnPattern() <em>Column Pattern</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColumnPattern()
   * @generated
   * @ordered
   */
  protected static final String COLUMN_PATTERN_EDEFAULT = null;

  /**
   * The cached value of the '{@link #getColumnPattern() <em>Column Pattern</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColumnPattern()
   * @generated
   * @ordered
   */
  protected String columnPattern = COLUMN_PATTERN_EDEFAULT;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FilterObjectTypeRuleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TableDSLPackage.Literals.FILTER_OBJECT_TYPE_RULE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String getColumnPattern()
  {
    return columnPattern;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setColumnPattern(String newColumnPattern)
  {
    String oldColumnPattern = columnPattern;
    columnPattern = newColumnPattern;
    if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TableDSLPackage.FILTER_OBJECT_TYPE_RULE__COLUMN_PATTERN, oldColumnPattern, columnPattern));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TableDSLPackage.FILTER_OBJECT_TYPE_RULE__COLUMN_PATTERN:
        return getColumnPattern();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TableDSLPackage.FILTER_OBJECT_TYPE_RULE__COLUMN_PATTERN:
        setColumnPattern((String)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TableDSLPackage.FILTER_OBJECT_TYPE_RULE__COLUMN_PATTERN:
        setColumnPattern(COLUMN_PATTERN_EDEFAULT);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TableDSLPackage.FILTER_OBJECT_TYPE_RULE__COLUMN_PATTERN:
        return COLUMN_PATTERN_EDEFAULT == null ? columnPattern != null : !COLUMN_PATTERN_EDEFAULT.equals(columnPattern);
    }
    return super.eIsSet(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public String toString()
  {
    if (eIsProxy()) return super.toString();

    StringBuilder result = new StringBuilder(super.toString());
    result.append(" (columnPattern: ");
    result.append(columnPattern);
    result.append(')');
    return result.toString();
  }

} //FilterObjectTypeRuleImpl
