/**
 * generated by Xtext 2.32.0
 */
package org.feup.els5.dsl.tableDSL.impl;

import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.ENotificationImpl;

import org.feup.els5.dsl.tableDSL.ColumnName;
import org.feup.els5.dsl.tableDSL.FilterObjectTypeRule;
import org.feup.els5.dsl.tableDSL.TableDSLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Filter Object Type Rule</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.feup.els5.dsl.tableDSL.impl.FilterObjectTypeRuleImpl#getColumnPattern <em>Column Pattern</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FilterObjectTypeRuleImpl extends FilterRuleImpl implements FilterObjectTypeRule
{
  /**
   * The cached value of the '{@link #getColumnPattern() <em>Column Pattern</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getColumnPattern()
   * @generated
   * @ordered
   */
  protected ColumnName columnPattern;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FilterObjectTypeRuleImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TableDSLPackage.Literals.FILTER_OBJECT_TYPE_RULE;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ColumnName getColumnPattern()
  {
    return columnPattern;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public NotificationChain basicSetColumnPattern(ColumnName newColumnPattern, NotificationChain msgs)
  {
    ColumnName oldColumnPattern = columnPattern;
    columnPattern = newColumnPattern;
    if (eNotificationRequired())
    {
      ENotificationImpl notification = new ENotificationImpl(this, Notification.SET, TableDSLPackage.FILTER_OBJECT_TYPE_RULE__COLUMN_PATTERN, oldColumnPattern, newColumnPattern);
      if (msgs == null) msgs = notification; else msgs.add(notification);
    }
    return msgs;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void setColumnPattern(ColumnName newColumnPattern)
  {
    if (newColumnPattern != columnPattern)
    {
      NotificationChain msgs = null;
      if (columnPattern != null)
        msgs = ((InternalEObject)columnPattern).eInverseRemove(this, EOPPOSITE_FEATURE_BASE - TableDSLPackage.FILTER_OBJECT_TYPE_RULE__COLUMN_PATTERN, null, msgs);
      if (newColumnPattern != null)
        msgs = ((InternalEObject)newColumnPattern).eInverseAdd(this, EOPPOSITE_FEATURE_BASE - TableDSLPackage.FILTER_OBJECT_TYPE_RULE__COLUMN_PATTERN, null, msgs);
      msgs = basicSetColumnPattern(newColumnPattern, msgs);
      if (msgs != null) msgs.dispatch();
    }
    else if (eNotificationRequired())
      eNotify(new ENotificationImpl(this, Notification.SET, TableDSLPackage.FILTER_OBJECT_TYPE_RULE__COLUMN_PATTERN, newColumnPattern, newColumnPattern));
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TableDSLPackage.FILTER_OBJECT_TYPE_RULE__COLUMN_PATTERN:
        return basicSetColumnPattern(null, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TableDSLPackage.FILTER_OBJECT_TYPE_RULE__COLUMN_PATTERN:
        return getColumnPattern();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TableDSLPackage.FILTER_OBJECT_TYPE_RULE__COLUMN_PATTERN:
        setColumnPattern((ColumnName)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TableDSLPackage.FILTER_OBJECT_TYPE_RULE__COLUMN_PATTERN:
        setColumnPattern((ColumnName)null);
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TableDSLPackage.FILTER_OBJECT_TYPE_RULE__COLUMN_PATTERN:
        return columnPattern != null;
    }
    return super.eIsSet(featureID);
  }

} //FilterObjectTypeRuleImpl
