/**
 * generated by Xtext 2.33.0
 */
package org.feup.els5.dsl.tableDSL.impl;

import java.util.Collection;

import org.eclipse.emf.common.notify.NotificationChain;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.InternalEObject;

import org.eclipse.emf.ecore.impl.MinimalEObjectImpl;

import org.eclipse.emf.ecore.util.EObjectContainmentEList;
import org.eclipse.emf.ecore.util.InternalEList;

import org.feup.els5.dsl.tableDSL.FilterExceptlist;
import org.feup.els5.dsl.tableDSL.FilterRule;
import org.feup.els5.dsl.tableDSL.TableDSLPackage;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model object '<em><b>Filter Exceptlist</b></em>'.
 * <!-- end-user-doc -->
 * <p>
 * The following features are implemented:
 * </p>
 * <ul>
 *   <li>{@link org.feup.els5.dsl.tableDSL.impl.FilterExceptlistImpl#getExceptlist <em>Exceptlist</em>}</li>
 * </ul>
 *
 * @generated
 */
public class FilterExceptlistImpl extends MinimalEObjectImpl.Container implements FilterExceptlist
{
  /**
   * The cached value of the '{@link #getExceptlist() <em>Exceptlist</em>}' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see #getExceptlist()
   * @generated
   * @ordered
   */
  protected EList<FilterRule> exceptlist;

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  protected FilterExceptlistImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  protected EClass eStaticClass()
  {
    return TableDSLPackage.Literals.FILTER_EXCEPTLIST;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EList<FilterRule> getExceptlist()
  {
    if (exceptlist == null)
    {
      exceptlist = new EObjectContainmentEList<FilterRule>(FilterRule.class, this, TableDSLPackage.FILTER_EXCEPTLIST__EXCEPTLIST);
    }
    return exceptlist;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public NotificationChain eInverseRemove(InternalEObject otherEnd, int featureID, NotificationChain msgs)
  {
    switch (featureID)
    {
      case TableDSLPackage.FILTER_EXCEPTLIST__EXCEPTLIST:
        return ((InternalEList<?>)getExceptlist()).basicRemove(otherEnd, msgs);
    }
    return super.eInverseRemove(otherEnd, featureID, msgs);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Object eGet(int featureID, boolean resolve, boolean coreType)
  {
    switch (featureID)
    {
      case TableDSLPackage.FILTER_EXCEPTLIST__EXCEPTLIST:
        return getExceptlist();
    }
    return super.eGet(featureID, resolve, coreType);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @SuppressWarnings("unchecked")
  @Override
  public void eSet(int featureID, Object newValue)
  {
    switch (featureID)
    {
      case TableDSLPackage.FILTER_EXCEPTLIST__EXCEPTLIST:
        getExceptlist().clear();
        getExceptlist().addAll((Collection<? extends FilterRule>)newValue);
        return;
    }
    super.eSet(featureID, newValue);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public void eUnset(int featureID)
  {
    switch (featureID)
    {
      case TableDSLPackage.FILTER_EXCEPTLIST__EXCEPTLIST:
        getExceptlist().clear();
        return;
    }
    super.eUnset(featureID);
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public boolean eIsSet(int featureID)
  {
    switch (featureID)
    {
      case TableDSLPackage.FILTER_EXCEPTLIST__EXCEPTLIST:
        return exceptlist != null && !exceptlist.isEmpty();
    }
    return super.eIsSet(featureID);
  }

} //FilterExceptlistImpl
