/**
 * generated by Xtext 2.33.0
 */
package org.feup.els5.dsl.tableDSL.impl;

import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;

import org.eclipse.emf.ecore.impl.EFactoryImpl;

import org.eclipse.emf.ecore.plugin.EcorePlugin;

import org.feup.els5.dsl.tableDSL.*;

/**
 * <!-- begin-user-doc -->
 * An implementation of the model <b>Factory</b>.
 * <!-- end-user-doc -->
 * @generated
 */
public class TableDSLFactoryImpl extends EFactoryImpl implements TableDSLFactory
{
  /**
   * Creates the default factory implementation.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public static TableDSLFactory init()
  {
    try
    {
      TableDSLFactory theTableDSLFactory = (TableDSLFactory)EPackage.Registry.INSTANCE.getEFactory(TableDSLPackage.eNS_URI);
      if (theTableDSLFactory != null)
      {
        return theTableDSLFactory;
      }
    }
    catch (Exception exception)
    {
      EcorePlugin.INSTANCE.log(exception);
    }
    return new TableDSLFactoryImpl();
  }

  /**
   * Creates an instance of the factory.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  public TableDSLFactoryImpl()
  {
    super();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public EObject create(EClass eClass)
  {
    switch (eClass.getClassifierID())
    {
      case TableDSLPackage.START: return createStart();
      case TableDSLPackage.CREATE_TABLE: return createCreateTable();
      case TableDSLPackage.TABLE_ACTION: return createTableAction();
      case TableDSLPackage.LOAD_DATA: return createLoadData();
      case TableDSLPackage.TABLE_INPUT_PATH: return createTableInputPath();
      case TableDSLPackage.OUTPUT: return createOutput();
      case TableDSLPackage.OPERATION: return createOperation();
      case TableDSLPackage.SELECT: return createSelect();
      case TableDSLPackage.RENAME_COLUMN: return createRenameColumn();
      case TableDSLPackage.RENAME_COLUMN_PAIR: return createRenameColumnPair();
      case TableDSLPackage.RENAME_COLUMN_TO_PAIR: return createRenameColumnToPair();
      case TableDSLPackage.RENAME_COLUMN_PREPEND_PAIR: return createRenameColumnPrependPair();
      case TableDSLPackage.RENAME_COLUMN_APPEND_PAIR: return createRenameColumnAppendPair();
      case TableDSLPackage.RENAME_COLUMN_REPLACE_PAIR: return createRenameColumnReplacePair();
      case TableDSLPackage.EXTRACT: return createExtract();
      case TableDSLPackage.EXTRACT_COLUMN_MAPPING: return createExtractColumnMapping();
      case TableDSLPackage.SELECTOR: return createSelector();
      case TableDSLPackage.KEY_SELECTOR: return createKeySelector();
      case TableDSLPackage.TOP_NSELECTOR: return createTopNSelector();
      case TableDSLPackage.COMPARATOR: return createComparator();
      case TableDSLPackage.SQUASH_ROWS: return createSquashRows();
      case TableDSLPackage.FILTER: return createFilter();
      case TableDSLPackage.FILTER_DENYLIST: return createFilterDenylist();
      case TableDSLPackage.FILTER_EXCEPTLIST: return createFilterExceptlist();
      case TableDSLPackage.FILTER_RULE: return createFilterRule();
      case TableDSLPackage.FILTER_COLUMN_RULE: return createFilterColumnRule();
      case TableDSLPackage.FILTER_OBJECT_TYPE_RULE: return createFilterObjectTypeRule();
      case TableDSLPackage.REDUCE: return createReduce();
      case TableDSLPackage.COLUMN_NAME: return createColumnName();
      case TableDSLPackage.OBJECT_TYPE_SELECTOR: return createObjectTypeSelector();
      default:
        throw new IllegalArgumentException("The class '" + eClass.getName() + "' is not a valid classifier");
    }
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Start createStart()
  {
    StartImpl start = new StartImpl();
    return start;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public CreateTable createCreateTable()
  {
    CreateTableImpl createTable = new CreateTableImpl();
    return createTable;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TableAction createTableAction()
  {
    TableActionImpl tableAction = new TableActionImpl();
    return tableAction;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public LoadData createLoadData()
  {
    LoadDataImpl loadData = new LoadDataImpl();
    return loadData;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TableInputPath createTableInputPath()
  {
    TableInputPathImpl tableInputPath = new TableInputPathImpl();
    return tableInputPath;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Output createOutput()
  {
    OutputImpl output = new OutputImpl();
    return output;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Operation createOperation()
  {
    OperationImpl operation = new OperationImpl();
    return operation;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Select createSelect()
  {
    SelectImpl select = new SelectImpl();
    return select;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RenameColumn createRenameColumn()
  {
    RenameColumnImpl renameColumn = new RenameColumnImpl();
    return renameColumn;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RenameColumnPair createRenameColumnPair()
  {
    RenameColumnPairImpl renameColumnPair = new RenameColumnPairImpl();
    return renameColumnPair;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RenameColumnToPair createRenameColumnToPair()
  {
    RenameColumnToPairImpl renameColumnToPair = new RenameColumnToPairImpl();
    return renameColumnToPair;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RenameColumnPrependPair createRenameColumnPrependPair()
  {
    RenameColumnPrependPairImpl renameColumnPrependPair = new RenameColumnPrependPairImpl();
    return renameColumnPrependPair;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RenameColumnAppendPair createRenameColumnAppendPair()
  {
    RenameColumnAppendPairImpl renameColumnAppendPair = new RenameColumnAppendPairImpl();
    return renameColumnAppendPair;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public RenameColumnReplacePair createRenameColumnReplacePair()
  {
    RenameColumnReplacePairImpl renameColumnReplacePair = new RenameColumnReplacePairImpl();
    return renameColumnReplacePair;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Extract createExtract()
  {
    ExtractImpl extract = new ExtractImpl();
    return extract;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ExtractColumnMapping createExtractColumnMapping()
  {
    ExtractColumnMappingImpl extractColumnMapping = new ExtractColumnMappingImpl();
    return extractColumnMapping;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Selector createSelector()
  {
    SelectorImpl selector = new SelectorImpl();
    return selector;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public KeySelector createKeySelector()
  {
    KeySelectorImpl keySelector = new KeySelectorImpl();
    return keySelector;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TopNSelector createTopNSelector()
  {
    TopNSelectorImpl topNSelector = new TopNSelectorImpl();
    return topNSelector;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Comparator createComparator()
  {
    ComparatorImpl comparator = new ComparatorImpl();
    return comparator;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public SquashRows createSquashRows()
  {
    SquashRowsImpl squashRows = new SquashRowsImpl();
    return squashRows;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Filter createFilter()
  {
    FilterImpl filter = new FilterImpl();
    return filter;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FilterDenylist createFilterDenylist()
  {
    FilterDenylistImpl filterDenylist = new FilterDenylistImpl();
    return filterDenylist;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FilterExceptlist createFilterExceptlist()
  {
    FilterExceptlistImpl filterExceptlist = new FilterExceptlistImpl();
    return filterExceptlist;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FilterRule createFilterRule()
  {
    FilterRuleImpl filterRule = new FilterRuleImpl();
    return filterRule;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FilterColumnRule createFilterColumnRule()
  {
    FilterColumnRuleImpl filterColumnRule = new FilterColumnRuleImpl();
    return filterColumnRule;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public FilterObjectTypeRule createFilterObjectTypeRule()
  {
    FilterObjectTypeRuleImpl filterObjectTypeRule = new FilterObjectTypeRuleImpl();
    return filterObjectTypeRule;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public Reduce createReduce()
  {
    ReduceImpl reduce = new ReduceImpl();
    return reduce;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ColumnName createColumnName()
  {
    ColumnNameImpl columnName = new ColumnNameImpl();
    return columnName;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public ObjectTypeSelector createObjectTypeSelector()
  {
    ObjectTypeSelectorImpl objectTypeSelector = new ObjectTypeSelectorImpl();
    return objectTypeSelector;
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  @Override
  public TableDSLPackage getTableDSLPackage()
  {
    return (TableDSLPackage)getEPackage();
  }

  /**
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @deprecated
   * @generated
   */
  @Deprecated
  public static TableDSLPackage getPackage()
  {
    return TableDSLPackage.eINSTANCE;
  }

} //TableDSLFactoryImpl
