/*
 * generated by Xtext 2.32.0
 */
package org.feup.els5.dsl;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class DSLRuntimeModule extends AbstractDSLRuntimeModule {
}
