/*
 * generated by Xtext 2.32.0
 */
package org.feup.els5.dsl.scoping;


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
public class DSLScopeProvider extends AbstractDSLScopeProvider {

}
