/*
 * generated by Xtext 2.32.0
 */
package org.feup.els5.dsl.ui.tests;

import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;
import org.feup.els5.dsl.ui.internal.DslActivator;

public class DSLUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return DslActivator.getInstance().getInjector("org.feup.els5.dsl.DSL");
	}

}
