/**
 * generated by Xtext 2.32.0
 */
package org.feup.els5.dsl.tableDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Comparator</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.feup.els5.dsl.tableDSL.Comparator#getKeys <em>Keys</em>}</li>
 * </ul>
 *
 * @see org.feup.els5.dsl.tableDSL.TableDSLPackage#getComparator()
 * @model
 * @generated
 */
public interface Comparator extends EObject
{
  /**
   * Returns the value of the '<em><b>Keys</b></em>' containment reference list.
   * The list contents are of type {@link org.feup.els5.dsl.tableDSL.ColumnName}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Keys</em>' containment reference list.
   * @see org.feup.els5.dsl.tableDSL.TableDSLPackage#getComparator_Keys()
   * @model containment="true"
   * @generated
   */
  EList<ColumnName> getKeys();

} // Comparator
