/**
 * generated by Xtext 2.33.0
 */
package org.feup.els5.dsl.tableDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Extract</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.feup.els5.dsl.tableDSL.Extract#getTargets <em>Targets</em>}</li>
 *   <li>{@link org.feup.els5.dsl.tableDSL.Extract#getSourceColumn <em>Source Column</em>}</li>
 *   <li>{@link org.feup.els5.dsl.tableDSL.Extract#getSelector <em>Selector</em>}</li>
 *   <li>{@link org.feup.els5.dsl.tableDSL.Extract#getComparator <em>Comparator</em>}</li>
 * </ul>
 *
 * @see org.feup.els5.dsl.tableDSL.TableDSLPackage#getExtract()
 * @model
 * @generated
 */
public interface Extract extends Operation
{
  /**
   * Returns the value of the '<em><b>Targets</b></em>' containment reference list.
   * The list contents are of type {@link org.feup.els5.dsl.tableDSL.ExtractColumnMapping}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Targets</em>' containment reference list.
   * @see org.feup.els5.dsl.tableDSL.TableDSLPackage#getExtract_Targets()
   * @model containment="true"
   * @generated
   */
  EList<ExtractColumnMapping> getTargets();

  /**
   * Returns the value of the '<em><b>Source Column</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Source Column</em>' attribute.
   * @see #setSourceColumn(String)
   * @see org.feup.els5.dsl.tableDSL.TableDSLPackage#getExtract_SourceColumn()
   * @model
   * @generated
   */
  String getSourceColumn();

  /**
   * Sets the value of the '{@link org.feup.els5.dsl.tableDSL.Extract#getSourceColumn <em>Source Column</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Source Column</em>' attribute.
   * @see #getSourceColumn()
   * @generated
   */
  void setSourceColumn(String value);

  /**
   * Returns the value of the '<em><b>Selector</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Selector</em>' containment reference.
   * @see #setSelector(Selector)
   * @see org.feup.els5.dsl.tableDSL.TableDSLPackage#getExtract_Selector()
   * @model containment="true"
   * @generated
   */
  Selector getSelector();

  /**
   * Sets the value of the '{@link org.feup.els5.dsl.tableDSL.Extract#getSelector <em>Selector</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Selector</em>' containment reference.
   * @see #getSelector()
   * @generated
   */
  void setSelector(Selector value);

  /**
   * Returns the value of the '<em><b>Comparator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Comparator</em>' containment reference.
   * @see #setComparator(Comparator)
   * @see org.feup.els5.dsl.tableDSL.TableDSLPackage#getExtract_Comparator()
   * @model containment="true"
   * @generated
   */
  Comparator getComparator();

  /**
   * Sets the value of the '{@link org.feup.els5.dsl.tableDSL.Extract#getComparator <em>Comparator</em>}' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Comparator</em>' containment reference.
   * @see #getComparator()
   * @generated
   */
  void setComparator(Comparator value);

} // Extract
