/**
 * generated by Xtext 2.33.0
 */
package org.feup.els5.dsl.tableDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Extract Column Mapping</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.feup.els5.dsl.tableDSL.ExtractColumnMapping#getTargetColumn <em>Target Column</em>}</li>
 *   <li>{@link org.feup.els5.dsl.tableDSL.ExtractColumnMapping#getNewName <em>New Name</em>}</li>
 * </ul>
 *
 * @see org.feup.els5.dsl.tableDSL.TableDSLPackage#getExtractColumnMapping()
 * @model
 * @generated
 */
public interface ExtractColumnMapping extends EObject
{
  /**
   * Returns the value of the '<em><b>Target Column</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Target Column</em>' attribute.
   * @see #setTargetColumn(String)
   * @see org.feup.els5.dsl.tableDSL.TableDSLPackage#getExtractColumnMapping_TargetColumn()
   * @model
   * @generated
   */
  String getTargetColumn();

  /**
   * Sets the value of the '{@link org.feup.els5.dsl.tableDSL.ExtractColumnMapping#getTargetColumn <em>Target Column</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Target Column</em>' attribute.
   * @see #getTargetColumn()
   * @generated
   */
  void setTargetColumn(String value);

  /**
   * Returns the value of the '<em><b>New Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>New Name</em>' attribute.
   * @see #setNewName(String)
   * @see org.feup.els5.dsl.tableDSL.TableDSLPackage#getExtractColumnMapping_NewName()
   * @model
   * @generated
   */
  String getNewName();

  /**
   * Sets the value of the '{@link org.feup.els5.dsl.tableDSL.ExtractColumnMapping#getNewName <em>New Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>New Name</em>' attribute.
   * @see #getNewName()
   * @generated
   */
  void setNewName(String value);

} // ExtractColumnMapping
