/**
 * generated by Xtext 2.33.0
 */
package org.feup.els5.dsl.tableDSL;

import org.eclipse.emf.common.util.EList;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Filter Exceptlist</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.feup.els5.dsl.tableDSL.FilterExceptlist#getExceptlist <em>Exceptlist</em>}</li>
 * </ul>
 *
 * @see org.feup.els5.dsl.tableDSL.TableDSLPackage#getFilterExceptlist()
 * @model
 * @generated
 */
public interface FilterExceptlist extends EObject
{
  /**
   * Returns the value of the '<em><b>Exceptlist</b></em>' containment reference list.
   * The list contents are of type {@link org.feup.els5.dsl.tableDSL.FilterRule}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Exceptlist</em>' containment reference list.
   * @see org.feup.els5.dsl.tableDSL.TableDSLPackage#getFilterExceptlist_Exceptlist()
   * @model containment="true"
   * @generated
   */
  EList<FilterRule> getExceptlist();

} // FilterExceptlist
