/**
 * generated by Xtext 2.32.0
 */
package org.feup.els5.dsl.tableDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Filter Object Type Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.feup.els5.dsl.tableDSL.FilterObjectTypeRule#getColumnPattern <em>Column Pattern</em>}</li>
 * </ul>
 *
 * @see org.feup.els5.dsl.tableDSL.TableDSLPackage#getFilterObjectTypeRule()
 * @model
 * @generated
 */
public interface FilterObjectTypeRule extends FilterRule
{
  /**
   * Returns the value of the '<em><b>Column Pattern</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Column Pattern</em>' attribute.
   * @see #setColumnPattern(String)
   * @see org.feup.els5.dsl.tableDSL.TableDSLPackage#getFilterObjectTypeRule_ColumnPattern()
   * @model
   * @generated
   */
  String getColumnPattern();

  /**
   * Sets the value of the '{@link org.feup.els5.dsl.tableDSL.FilterObjectTypeRule#getColumnPattern <em>Column Pattern</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Column Pattern</em>' attribute.
   * @see #getColumnPattern()
   * @generated
   */
  void setColumnPattern(String value);

} // FilterObjectTypeRule
