/**
 * generated by Xtext 2.32.0
 */
package org.feup.els5.dsl.tableDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Filter</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.feup.els5.dsl.tableDSL.Filter#getPlaceholder <em>Placeholder</em>}</li>
 * </ul>
 *
 * @see org.feup.els5.dsl.tableDSL.TableDSLPackage#getFilter()
 * @model
 * @generated
 */
public interface Filter extends Operation
{
  /**
   * Returns the value of the '<em><b>Placeholder</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Placeholder</em>' attribute.
   * @see #setPlaceholder(String)
   * @see org.feup.els5.dsl.tableDSL.TableDSLPackage#getFilter_Placeholder()
   * @model
   * @generated
   */
  String getPlaceholder();

  /**
   * Sets the value of the '{@link org.feup.els5.dsl.tableDSL.Filter#getPlaceholder <em>Placeholder</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Placeholder</em>' attribute.
   * @see #getPlaceholder()
   * @generated
   */
  void setPlaceholder(String value);

} // Filter
