/**
 * generated by Xtext 2.32.0
 */
package org.feup.els5.dsl.tableDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Filter Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.feup.els5.dsl.tableDSL.TableDSLPackage#getFilterRule()
 * @model
 * @generated
 */
public interface FilterRule extends EObject
{
} // FilterRule
