/**
 * generated by Xtext 2.32.0
 */
package org.feup.els5.dsl.tableDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Filter Column Rule</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.feup.els5.dsl.tableDSL.FilterColumnRule#getColumnPatterns <em>Column Patterns</em>}</li>
 * </ul>
 *
 * @see org.feup.els5.dsl.tableDSL.TableDSLPackage#getFilterColumnRule()
 * @model
 * @generated
 */
public interface FilterColumnRule extends FilterRule
{
  /**
   * Returns the value of the '<em><b>Column Patterns</b></em>' containment reference list.
   * The list contents are of type {@link org.feup.els5.dsl.tableDSL.ColumnName}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Column Patterns</em>' containment reference list.
   * @see org.feup.els5.dsl.tableDSL.TableDSLPackage#getFilterColumnRule_ColumnPatterns()
   * @model containment="true"
   * @generated
   */
  EList<ColumnName> getColumnPatterns();

} // FilterColumnRule
