/**
 * generated by Xtext 2.33.0
 */
package org.feup.els5.dsl.tableDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Operation</b></em>'.
 * <!-- end-user-doc -->
 *
 *
 * @see org.feup.els5.dsl.tableDSL.TableDSLPackage#getOperation()
 * @model
 * @generated
 */
public interface Operation extends TableAction
{
} // Operation
