/**
 * generated by Xtext 2.32.0
 */
package org.feup.els5.dsl.tableDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rename Column</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.feup.els5.dsl.tableDSL.RenameColumn#getOldName <em>Old Name</em>}</li>
 *   <li>{@link org.feup.els5.dsl.tableDSL.RenameColumn#getNewName <em>New Name</em>}</li>
 * </ul>
 *
 * @see org.feup.els5.dsl.tableDSL.TableDSLPackage#getRenameColumn()
 * @model
 * @generated
 */
public interface RenameColumn extends Operation
{
  /**
   * Returns the value of the '<em><b>Old Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Old Name</em>' attribute.
   * @see #setOldName(String)
   * @see org.feup.els5.dsl.tableDSL.TableDSLPackage#getRenameColumn_OldName()
   * @model
   * @generated
   */
  String getOldName();

  /**
   * Sets the value of the '{@link org.feup.els5.dsl.tableDSL.RenameColumn#getOldName <em>Old Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Old Name</em>' attribute.
   * @see #getOldName()
   * @generated
   */
  void setOldName(String value);

  /**
   * Returns the value of the '<em><b>New Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>New Name</em>' attribute.
   * @see #setNewName(String)
   * @see org.feup.els5.dsl.tableDSL.TableDSLPackage#getRenameColumn_NewName()
   * @model
   * @generated
   */
  String getNewName();

  /**
   * Sets the value of the '{@link org.feup.els5.dsl.tableDSL.RenameColumn#getNewName <em>New Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>New Name</em>' attribute.
   * @see #getNewName()
   * @generated
   */
  void setNewName(String value);

} // RenameColumn
