/**
 * generated by Xtext 2.32.0
 */
package org.feup.els5.dsl.tableDSL;

import org.eclipse.emf.ecore.EObject;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Rename Column Pair</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.feup.els5.dsl.tableDSL.RenameColumnPair#getOldName <em>Old Name</em>}</li>
 * </ul>
 *
 * @see org.feup.els5.dsl.tableDSL.TableDSLPackage#getRenameColumnPair()
 * @model
 * @generated
 */
public interface RenameColumnPair extends EObject
{
  /**
   * Returns the value of the '<em><b>Old Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Old Name</em>' attribute.
   * @see #setOldName(String)
   * @see org.feup.els5.dsl.tableDSL.TableDSLPackage#getRenameColumnPair_OldName()
   * @model
   * @generated
   */
  String getOldName();

  /**
   * Sets the value of the '{@link org.feup.els5.dsl.tableDSL.RenameColumnPair#getOldName <em>Old Name</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>Old Name</em>' attribute.
   * @see #getOldName()
   * @generated
   */
  void setOldName(String value);

} // RenameColumnPair
