/**
 * generated by Xtext 2.32.0
 */
package org.feup.els5.dsl.tableDSL;

import org.eclipse.emf.common.util.EList;

/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Table Input Path</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.feup.els5.dsl.tableDSL.TableInputPath#getPathPatterns <em>Path Patterns</em>}</li>
 * </ul>
 *
 * @see org.feup.els5.dsl.tableDSL.TableDSLPackage#getTableInputPath()
 * @model
 * @generated
 */
public interface TableInputPath extends CreateTable, LoadData
{
  /**
   * Returns the value of the '<em><b>Path Patterns</b></em>' attribute list.
   * The list contents are of type {@link java.lang.String}.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>Path Patterns</em>' attribute list.
   * @see org.feup.els5.dsl.tableDSL.TableDSLPackage#getTableInputPath_PathPatterns()
   * @model unique="false"
   * @generated
   */
  EList<String> getPathPatterns();

} // TableInputPath
