/**
 * generated by Xtext 2.32.0
 */
package org.feup.els5.dsl.tableDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.feup.els5.dsl.tableDSL.TableDSLFactory
 * @model kind="package"
 * @generated
 */
public interface TableDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "tableDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.feup.org/els5/dsl/TableDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "tableDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TableDSLPackage eINSTANCE = org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.StartImpl <em>Start</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.StartImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getStart()
   * @generated
   */
  int START = 0;

  /**
   * The feature id for the '<em><b>Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int START__ACTIONS = 0;

  /**
   * The number of structural features of the '<em>Start</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int START_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.CreateTableImpl <em>Create Table</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.CreateTableImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getCreateTable()
   * @generated
   */
  int CREATE_TABLE = 1;

  /**
   * The number of structural features of the '<em>Create Table</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_TABLE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.TableActionImpl <em>Table Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.TableActionImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getTableAction()
   * @generated
   */
  int TABLE_ACTION = 2;

  /**
   * The number of structural features of the '<em>Table Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_ACTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.LoadDataImpl <em>Load Data</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.LoadDataImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getLoadData()
   * @generated
   */
  int LOAD_DATA = 3;

  /**
   * The number of structural features of the '<em>Load Data</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD_DATA_FEATURE_COUNT = TABLE_ACTION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.TableInputPathImpl <em>Table Input Path</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.TableInputPathImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getTableInputPath()
   * @generated
   */
  int TABLE_INPUT_PATH = 4;

  /**
   * The feature id for the '<em><b>Path Patterns</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_INPUT_PATH__PATH_PATTERNS = CREATE_TABLE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Table Input Path</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_INPUT_PATH_FEATURE_COUNT = CREATE_TABLE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.OutputImpl <em>Output</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.OutputImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getOutput()
   * @generated
   */
  int OUTPUT = 5;

  /**
   * The feature id for the '<em><b>Output Paths</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT__OUTPUT_PATHS = TABLE_ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Output</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT_FEATURE_COUNT = TABLE_ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.OperationImpl <em>Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.OperationImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getOperation()
   * @generated
   */
  int OPERATION = 6;

  /**
   * The number of structural features of the '<em>Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_FEATURE_COUNT = TABLE_ACTION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.SelectImpl <em>Select</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.SelectImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getSelect()
   * @generated
   */
  int SELECT = 7;

  /**
   * The feature id for the '<em><b>Columns Patterns</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT__COLUMNS_PATTERNS = OPERATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Column Patterns</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT__COLUMN_PATTERNS = OPERATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Select</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.RenameColumnImpl <em>Rename Column</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.RenameColumnImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getRenameColumn()
   * @generated
   */
  int RENAME_COLUMN = 8;

  /**
   * The feature id for the '<em><b>Rename Tuples</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RENAME_COLUMN__RENAME_TUPLES = OPERATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Rename Column</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RENAME_COLUMN_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.RenameColumnPairImpl <em>Rename Column Pair</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.RenameColumnPairImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getRenameColumnPair()
   * @generated
   */
  int RENAME_COLUMN_PAIR = 9;

  /**
   * The feature id for the '<em><b>Old Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RENAME_COLUMN_PAIR__OLD_NAME = 0;

  /**
   * The number of structural features of the '<em>Rename Column Pair</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RENAME_COLUMN_PAIR_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.RenameColumnToPairImpl <em>Rename Column To Pair</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.RenameColumnToPairImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getRenameColumnToPair()
   * @generated
   */
  int RENAME_COLUMN_TO_PAIR = 10;

  /**
   * The feature id for the '<em><b>Old Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RENAME_COLUMN_TO_PAIR__OLD_NAME = RENAME_COLUMN_PAIR__OLD_NAME;

  /**
   * The feature id for the '<em><b>New Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RENAME_COLUMN_TO_PAIR__NEW_NAME = RENAME_COLUMN_PAIR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Rename Column To Pair</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RENAME_COLUMN_TO_PAIR_FEATURE_COUNT = RENAME_COLUMN_PAIR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.RenameColumnPrependPairImpl <em>Rename Column Prepend Pair</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.RenameColumnPrependPairImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getRenameColumnPrependPair()
   * @generated
   */
  int RENAME_COLUMN_PREPEND_PAIR = 11;

  /**
   * The feature id for the '<em><b>Old Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RENAME_COLUMN_PREPEND_PAIR__OLD_NAME = RENAME_COLUMN_PAIR__OLD_NAME;

  /**
   * The feature id for the '<em><b>Prefix</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RENAME_COLUMN_PREPEND_PAIR__PREFIX = RENAME_COLUMN_PAIR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Rename Column Prepend Pair</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RENAME_COLUMN_PREPEND_PAIR_FEATURE_COUNT = RENAME_COLUMN_PAIR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.RenameColumnAppendPairImpl <em>Rename Column Append Pair</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.RenameColumnAppendPairImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getRenameColumnAppendPair()
   * @generated
   */
  int RENAME_COLUMN_APPEND_PAIR = 12;

  /**
   * The feature id for the '<em><b>Old Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RENAME_COLUMN_APPEND_PAIR__OLD_NAME = RENAME_COLUMN_PAIR__OLD_NAME;

  /**
   * The feature id for the '<em><b>Suffix</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RENAME_COLUMN_APPEND_PAIR__SUFFIX = RENAME_COLUMN_PAIR_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Rename Column Append Pair</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RENAME_COLUMN_APPEND_PAIR_FEATURE_COUNT = RENAME_COLUMN_PAIR_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.ExtractImpl <em>Extract</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.ExtractImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getExtract()
   * @generated
   */
  int EXTRACT = 13;

  /**
   * The feature id for the '<em><b>Target Columns</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTRACT__TARGET_COLUMNS = OPERATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Source Column</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTRACT__SOURCE_COLUMN = OPERATION_FEATURE_COUNT + 1;

  /**
   * The feature id for the '<em><b>Selector</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTRACT__SELECTOR = OPERATION_FEATURE_COUNT + 2;

  /**
   * The feature id for the '<em><b>Comparator</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTRACT__COMPARATOR = OPERATION_FEATURE_COUNT + 3;

  /**
   * The number of structural features of the '<em>Extract</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTRACT_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 4;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.SelectorImpl <em>Selector</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.SelectorImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getSelector()
   * @generated
   */
  int SELECTOR = 14;

  /**
   * The feature id for the '<em><b>N</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR__N = 0;

  /**
   * The number of structural features of the '<em>Selector</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECTOR_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.ComparatorImpl <em>Comparator</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.ComparatorImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getComparator()
   * @generated
   */
  int COMPARATOR = 15;

  /**
   * The feature id for the '<em><b>Keys</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARATOR__KEYS = 0;

  /**
   * The number of structural features of the '<em>Comparator</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COMPARATOR_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.SquashRowsImpl <em>Squash Rows</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.SquashRowsImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getSquashRows()
   * @generated
   */
  int SQUASH_ROWS = 16;

  /**
   * The feature id for the '<em><b>Columns</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SQUASH_ROWS__COLUMNS = OPERATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Squash Rows</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SQUASH_ROWS_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.FilterImpl <em>Filter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.FilterImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getFilter()
   * @generated
   */
  int FILTER = 17;

  /**
   * The feature id for the '<em><b>Denylist</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER__DENYLIST = OPERATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Exceptlist</b></em>' containment reference.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER__EXCEPTLIST = OPERATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Filter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.FilterDenylistImpl <em>Filter Denylist</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.FilterDenylistImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getFilterDenylist()
   * @generated
   */
  int FILTER_DENYLIST = 18;

  /**
   * The feature id for the '<em><b>Denylist</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER_DENYLIST__DENYLIST = 0;

  /**
   * The number of structural features of the '<em>Filter Denylist</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER_DENYLIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.FilterExceptlistImpl <em>Filter Exceptlist</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.FilterExceptlistImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getFilterExceptlist()
   * @generated
   */
  int FILTER_EXCEPTLIST = 19;

  /**
   * The feature id for the '<em><b>Exceptlist</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER_EXCEPTLIST__EXCEPTLIST = 0;

  /**
   * The number of structural features of the '<em>Filter Exceptlist</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER_EXCEPTLIST_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.FilterRuleImpl <em>Filter Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.FilterRuleImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getFilterRule()
   * @generated
   */
  int FILTER_RULE = 20;

  /**
   * The number of structural features of the '<em>Filter Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER_RULE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.FilterColumnRuleImpl <em>Filter Column Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.FilterColumnRuleImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getFilterColumnRule()
   * @generated
   */
  int FILTER_COLUMN_RULE = 21;

  /**
   * The feature id for the '<em><b>Column Patterns</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER_COLUMN_RULE__COLUMN_PATTERNS = FILTER_RULE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Filter Column Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER_COLUMN_RULE_FEATURE_COUNT = FILTER_RULE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.FilterObjectTypeRuleImpl <em>Filter Object Type Rule</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.FilterObjectTypeRuleImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getFilterObjectTypeRule()
   * @generated
   */
  int FILTER_OBJECT_TYPE_RULE = 22;

  /**
   * The feature id for the '<em><b>Object Classes</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER_OBJECT_TYPE_RULE__OBJECT_CLASSES = FILTER_RULE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Filter Object Type Rule</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER_OBJECT_TYPE_RULE_FEATURE_COUNT = FILTER_RULE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.ColumnNameImpl <em>Column Name</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.ColumnNameImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getColumnName()
   * @generated
   */
  int COLUMN_NAME = 23;

  /**
   * The feature id for the '<em><b>Column Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_NAME__COLUMN_NAME = 0;

  /**
   * The number of structural features of the '<em>Column Name</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int COLUMN_NAME_FEATURE_COUNT = 1;


  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.Start <em>Start</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Start</em>'.
   * @see org.feup.els5.dsl.tableDSL.Start
   * @generated
   */
  EClass getStart();

  /**
   * Returns the meta object for the containment reference list '{@link org.feup.els5.dsl.tableDSL.Start#getActions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actions</em>'.
   * @see org.feup.els5.dsl.tableDSL.Start#getActions()
   * @see #getStart()
   * @generated
   */
  EReference getStart_Actions();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.CreateTable <em>Create Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Create Table</em>'.
   * @see org.feup.els5.dsl.tableDSL.CreateTable
   * @generated
   */
  EClass getCreateTable();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.TableAction <em>Table Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Table Action</em>'.
   * @see org.feup.els5.dsl.tableDSL.TableAction
   * @generated
   */
  EClass getTableAction();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.LoadData <em>Load Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Load Data</em>'.
   * @see org.feup.els5.dsl.tableDSL.LoadData
   * @generated
   */
  EClass getLoadData();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.TableInputPath <em>Table Input Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Table Input Path</em>'.
   * @see org.feup.els5.dsl.tableDSL.TableInputPath
   * @generated
   */
  EClass getTableInputPath();

  /**
   * Returns the meta object for the attribute list '{@link org.feup.els5.dsl.tableDSL.TableInputPath#getPathPatterns <em>Path Patterns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Path Patterns</em>'.
   * @see org.feup.els5.dsl.tableDSL.TableInputPath#getPathPatterns()
   * @see #getTableInputPath()
   * @generated
   */
  EAttribute getTableInputPath_PathPatterns();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.Output <em>Output</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Output</em>'.
   * @see org.feup.els5.dsl.tableDSL.Output
   * @generated
   */
  EClass getOutput();

  /**
   * Returns the meta object for the attribute list '{@link org.feup.els5.dsl.tableDSL.Output#getOutputPaths <em>Output Paths</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Output Paths</em>'.
   * @see org.feup.els5.dsl.tableDSL.Output#getOutputPaths()
   * @see #getOutput()
   * @generated
   */
  EAttribute getOutput_OutputPaths();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.Operation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation</em>'.
   * @see org.feup.els5.dsl.tableDSL.Operation
   * @generated
   */
  EClass getOperation();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.Select <em>Select</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Select</em>'.
   * @see org.feup.els5.dsl.tableDSL.Select
   * @generated
   */
  EClass getSelect();

  /**
   * Returns the meta object for the containment reference list '{@link org.feup.els5.dsl.tableDSL.Select#getColumnsPatterns <em>Columns Patterns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Columns Patterns</em>'.
   * @see org.feup.els5.dsl.tableDSL.Select#getColumnsPatterns()
   * @see #getSelect()
   * @generated
   */
  EReference getSelect_ColumnsPatterns();

  /**
   * Returns the meta object for the containment reference list '{@link org.feup.els5.dsl.tableDSL.Select#getColumnPatterns <em>Column Patterns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Column Patterns</em>'.
   * @see org.feup.els5.dsl.tableDSL.Select#getColumnPatterns()
   * @see #getSelect()
   * @generated
   */
  EReference getSelect_ColumnPatterns();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.RenameColumn <em>Rename Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rename Column</em>'.
   * @see org.feup.els5.dsl.tableDSL.RenameColumn
   * @generated
   */
  EClass getRenameColumn();

  /**
   * Returns the meta object for the containment reference list '{@link org.feup.els5.dsl.tableDSL.RenameColumn#getRenameTuples <em>Rename Tuples</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Rename Tuples</em>'.
   * @see org.feup.els5.dsl.tableDSL.RenameColumn#getRenameTuples()
   * @see #getRenameColumn()
   * @generated
   */
  EReference getRenameColumn_RenameTuples();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.RenameColumnPair <em>Rename Column Pair</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rename Column Pair</em>'.
   * @see org.feup.els5.dsl.tableDSL.RenameColumnPair
   * @generated
   */
  EClass getRenameColumnPair();

  /**
   * Returns the meta object for the attribute '{@link org.feup.els5.dsl.tableDSL.RenameColumnPair#getOldName <em>Old Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Old Name</em>'.
   * @see org.feup.els5.dsl.tableDSL.RenameColumnPair#getOldName()
   * @see #getRenameColumnPair()
   * @generated
   */
  EAttribute getRenameColumnPair_OldName();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.RenameColumnToPair <em>Rename Column To Pair</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rename Column To Pair</em>'.
   * @see org.feup.els5.dsl.tableDSL.RenameColumnToPair
   * @generated
   */
  EClass getRenameColumnToPair();

  /**
   * Returns the meta object for the attribute '{@link org.feup.els5.dsl.tableDSL.RenameColumnToPair#getNewName <em>New Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>New Name</em>'.
   * @see org.feup.els5.dsl.tableDSL.RenameColumnToPair#getNewName()
   * @see #getRenameColumnToPair()
   * @generated
   */
  EAttribute getRenameColumnToPair_NewName();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.RenameColumnPrependPair <em>Rename Column Prepend Pair</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rename Column Prepend Pair</em>'.
   * @see org.feup.els5.dsl.tableDSL.RenameColumnPrependPair
   * @generated
   */
  EClass getRenameColumnPrependPair();

  /**
   * Returns the meta object for the attribute '{@link org.feup.els5.dsl.tableDSL.RenameColumnPrependPair#getPrefix <em>Prefix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Prefix</em>'.
   * @see org.feup.els5.dsl.tableDSL.RenameColumnPrependPair#getPrefix()
   * @see #getRenameColumnPrependPair()
   * @generated
   */
  EAttribute getRenameColumnPrependPair_Prefix();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.RenameColumnAppendPair <em>Rename Column Append Pair</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rename Column Append Pair</em>'.
   * @see org.feup.els5.dsl.tableDSL.RenameColumnAppendPair
   * @generated
   */
  EClass getRenameColumnAppendPair();

  /**
   * Returns the meta object for the attribute '{@link org.feup.els5.dsl.tableDSL.RenameColumnAppendPair#getSuffix <em>Suffix</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Suffix</em>'.
   * @see org.feup.els5.dsl.tableDSL.RenameColumnAppendPair#getSuffix()
   * @see #getRenameColumnAppendPair()
   * @generated
   */
  EAttribute getRenameColumnAppendPair_Suffix();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.Extract <em>Extract</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Extract</em>'.
   * @see org.feup.els5.dsl.tableDSL.Extract
   * @generated
   */
  EClass getExtract();

  /**
   * Returns the meta object for the attribute list '{@link org.feup.els5.dsl.tableDSL.Extract#getTargetColumns <em>Target Columns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Target Columns</em>'.
   * @see org.feup.els5.dsl.tableDSL.Extract#getTargetColumns()
   * @see #getExtract()
   * @generated
   */
  EAttribute getExtract_TargetColumns();

  /**
   * Returns the meta object for the attribute '{@link org.feup.els5.dsl.tableDSL.Extract#getSourceColumn <em>Source Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Source Column</em>'.
   * @see org.feup.els5.dsl.tableDSL.Extract#getSourceColumn()
   * @see #getExtract()
   * @generated
   */
  EAttribute getExtract_SourceColumn();

  /**
   * Returns the meta object for the containment reference '{@link org.feup.els5.dsl.tableDSL.Extract#getSelector <em>Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Selector</em>'.
   * @see org.feup.els5.dsl.tableDSL.Extract#getSelector()
   * @see #getExtract()
   * @generated
   */
  EReference getExtract_Selector();

  /**
   * Returns the meta object for the containment reference '{@link org.feup.els5.dsl.tableDSL.Extract#getComparator <em>Comparator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Comparator</em>'.
   * @see org.feup.els5.dsl.tableDSL.Extract#getComparator()
   * @see #getExtract()
   * @generated
   */
  EReference getExtract_Comparator();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.Selector <em>Selector</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Selector</em>'.
   * @see org.feup.els5.dsl.tableDSL.Selector
   * @generated
   */
  EClass getSelector();

  /**
   * Returns the meta object for the attribute '{@link org.feup.els5.dsl.tableDSL.Selector#getN <em>N</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>N</em>'.
   * @see org.feup.els5.dsl.tableDSL.Selector#getN()
   * @see #getSelector()
   * @generated
   */
  EAttribute getSelector_N();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.Comparator <em>Comparator</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Comparator</em>'.
   * @see org.feup.els5.dsl.tableDSL.Comparator
   * @generated
   */
  EClass getComparator();

  /**
   * Returns the meta object for the containment reference list '{@link org.feup.els5.dsl.tableDSL.Comparator#getKeys <em>Keys</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Keys</em>'.
   * @see org.feup.els5.dsl.tableDSL.Comparator#getKeys()
   * @see #getComparator()
   * @generated
   */
  EReference getComparator_Keys();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.SquashRows <em>Squash Rows</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Squash Rows</em>'.
   * @see org.feup.els5.dsl.tableDSL.SquashRows
   * @generated
   */
  EClass getSquashRows();

  /**
   * Returns the meta object for the containment reference list '{@link org.feup.els5.dsl.tableDSL.SquashRows#getColumns <em>Columns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Columns</em>'.
   * @see org.feup.els5.dsl.tableDSL.SquashRows#getColumns()
   * @see #getSquashRows()
   * @generated
   */
  EReference getSquashRows_Columns();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.Filter <em>Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Filter</em>'.
   * @see org.feup.els5.dsl.tableDSL.Filter
   * @generated
   */
  EClass getFilter();

  /**
   * Returns the meta object for the containment reference '{@link org.feup.els5.dsl.tableDSL.Filter#getDenylist <em>Denylist</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Denylist</em>'.
   * @see org.feup.els5.dsl.tableDSL.Filter#getDenylist()
   * @see #getFilter()
   * @generated
   */
  EReference getFilter_Denylist();

  /**
   * Returns the meta object for the containment reference '{@link org.feup.els5.dsl.tableDSL.Filter#getExceptlist <em>Exceptlist</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference '<em>Exceptlist</em>'.
   * @see org.feup.els5.dsl.tableDSL.Filter#getExceptlist()
   * @see #getFilter()
   * @generated
   */
  EReference getFilter_Exceptlist();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.FilterDenylist <em>Filter Denylist</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Filter Denylist</em>'.
   * @see org.feup.els5.dsl.tableDSL.FilterDenylist
   * @generated
   */
  EClass getFilterDenylist();

  /**
   * Returns the meta object for the containment reference list '{@link org.feup.els5.dsl.tableDSL.FilterDenylist#getDenylist <em>Denylist</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Denylist</em>'.
   * @see org.feup.els5.dsl.tableDSL.FilterDenylist#getDenylist()
   * @see #getFilterDenylist()
   * @generated
   */
  EReference getFilterDenylist_Denylist();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.FilterExceptlist <em>Filter Exceptlist</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Filter Exceptlist</em>'.
   * @see org.feup.els5.dsl.tableDSL.FilterExceptlist
   * @generated
   */
  EClass getFilterExceptlist();

  /**
   * Returns the meta object for the containment reference list '{@link org.feup.els5.dsl.tableDSL.FilterExceptlist#getExceptlist <em>Exceptlist</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Exceptlist</em>'.
   * @see org.feup.els5.dsl.tableDSL.FilterExceptlist#getExceptlist()
   * @see #getFilterExceptlist()
   * @generated
   */
  EReference getFilterExceptlist_Exceptlist();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.FilterRule <em>Filter Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Filter Rule</em>'.
   * @see org.feup.els5.dsl.tableDSL.FilterRule
   * @generated
   */
  EClass getFilterRule();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.FilterColumnRule <em>Filter Column Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Filter Column Rule</em>'.
   * @see org.feup.els5.dsl.tableDSL.FilterColumnRule
   * @generated
   */
  EClass getFilterColumnRule();

  /**
   * Returns the meta object for the containment reference list '{@link org.feup.els5.dsl.tableDSL.FilterColumnRule#getColumnPatterns <em>Column Patterns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Column Patterns</em>'.
   * @see org.feup.els5.dsl.tableDSL.FilterColumnRule#getColumnPatterns()
   * @see #getFilterColumnRule()
   * @generated
   */
  EReference getFilterColumnRule_ColumnPatterns();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.FilterObjectTypeRule <em>Filter Object Type Rule</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Filter Object Type Rule</em>'.
   * @see org.feup.els5.dsl.tableDSL.FilterObjectTypeRule
   * @generated
   */
  EClass getFilterObjectTypeRule();

  /**
   * Returns the meta object for the attribute list '{@link org.feup.els5.dsl.tableDSL.FilterObjectTypeRule#getObjectClasses <em>Object Classes</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Object Classes</em>'.
   * @see org.feup.els5.dsl.tableDSL.FilterObjectTypeRule#getObjectClasses()
   * @see #getFilterObjectTypeRule()
   * @generated
   */
  EAttribute getFilterObjectTypeRule_ObjectClasses();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.ColumnName <em>Column Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Column Name</em>'.
   * @see org.feup.els5.dsl.tableDSL.ColumnName
   * @generated
   */
  EClass getColumnName();

  /**
   * Returns the meta object for the attribute '{@link org.feup.els5.dsl.tableDSL.ColumnName#getColumnName <em>Column Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Column Name</em>'.
   * @see org.feup.els5.dsl.tableDSL.ColumnName#getColumnName()
   * @see #getColumnName()
   * @generated
   */
  EAttribute getColumnName_ColumnName();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TableDSLFactory getTableDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.StartImpl <em>Start</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.StartImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getStart()
     * @generated
     */
    EClass START = eINSTANCE.getStart();

    /**
     * The meta object literal for the '<em><b>Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference START__ACTIONS = eINSTANCE.getStart_Actions();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.CreateTableImpl <em>Create Table</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.CreateTableImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getCreateTable()
     * @generated
     */
    EClass CREATE_TABLE = eINSTANCE.getCreateTable();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.TableActionImpl <em>Table Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.TableActionImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getTableAction()
     * @generated
     */
    EClass TABLE_ACTION = eINSTANCE.getTableAction();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.LoadDataImpl <em>Load Data</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.LoadDataImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getLoadData()
     * @generated
     */
    EClass LOAD_DATA = eINSTANCE.getLoadData();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.TableInputPathImpl <em>Table Input Path</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.TableInputPathImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getTableInputPath()
     * @generated
     */
    EClass TABLE_INPUT_PATH = eINSTANCE.getTableInputPath();

    /**
     * The meta object literal for the '<em><b>Path Patterns</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TABLE_INPUT_PATH__PATH_PATTERNS = eINSTANCE.getTableInputPath_PathPatterns();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.OutputImpl <em>Output</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.OutputImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getOutput()
     * @generated
     */
    EClass OUTPUT = eINSTANCE.getOutput();

    /**
     * The meta object literal for the '<em><b>Output Paths</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OUTPUT__OUTPUT_PATHS = eINSTANCE.getOutput_OutputPaths();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.OperationImpl <em>Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.OperationImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getOperation()
     * @generated
     */
    EClass OPERATION = eINSTANCE.getOperation();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.SelectImpl <em>Select</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.SelectImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getSelect()
     * @generated
     */
    EClass SELECT = eINSTANCE.getSelect();

    /**
     * The meta object literal for the '<em><b>Columns Patterns</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT__COLUMNS_PATTERNS = eINSTANCE.getSelect_ColumnsPatterns();

    /**
     * The meta object literal for the '<em><b>Column Patterns</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SELECT__COLUMN_PATTERNS = eINSTANCE.getSelect_ColumnPatterns();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.RenameColumnImpl <em>Rename Column</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.RenameColumnImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getRenameColumn()
     * @generated
     */
    EClass RENAME_COLUMN = eINSTANCE.getRenameColumn();

    /**
     * The meta object literal for the '<em><b>Rename Tuples</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference RENAME_COLUMN__RENAME_TUPLES = eINSTANCE.getRenameColumn_RenameTuples();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.RenameColumnPairImpl <em>Rename Column Pair</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.RenameColumnPairImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getRenameColumnPair()
     * @generated
     */
    EClass RENAME_COLUMN_PAIR = eINSTANCE.getRenameColumnPair();

    /**
     * The meta object literal for the '<em><b>Old Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RENAME_COLUMN_PAIR__OLD_NAME = eINSTANCE.getRenameColumnPair_OldName();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.RenameColumnToPairImpl <em>Rename Column To Pair</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.RenameColumnToPairImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getRenameColumnToPair()
     * @generated
     */
    EClass RENAME_COLUMN_TO_PAIR = eINSTANCE.getRenameColumnToPair();

    /**
     * The meta object literal for the '<em><b>New Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RENAME_COLUMN_TO_PAIR__NEW_NAME = eINSTANCE.getRenameColumnToPair_NewName();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.RenameColumnPrependPairImpl <em>Rename Column Prepend Pair</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.RenameColumnPrependPairImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getRenameColumnPrependPair()
     * @generated
     */
    EClass RENAME_COLUMN_PREPEND_PAIR = eINSTANCE.getRenameColumnPrependPair();

    /**
     * The meta object literal for the '<em><b>Prefix</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RENAME_COLUMN_PREPEND_PAIR__PREFIX = eINSTANCE.getRenameColumnPrependPair_Prefix();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.RenameColumnAppendPairImpl <em>Rename Column Append Pair</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.RenameColumnAppendPairImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getRenameColumnAppendPair()
     * @generated
     */
    EClass RENAME_COLUMN_APPEND_PAIR = eINSTANCE.getRenameColumnAppendPair();

    /**
     * The meta object literal for the '<em><b>Suffix</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RENAME_COLUMN_APPEND_PAIR__SUFFIX = eINSTANCE.getRenameColumnAppendPair_Suffix();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.ExtractImpl <em>Extract</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.ExtractImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getExtract()
     * @generated
     */
    EClass EXTRACT = eINSTANCE.getExtract();

    /**
     * The meta object literal for the '<em><b>Target Columns</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXTRACT__TARGET_COLUMNS = eINSTANCE.getExtract_TargetColumns();

    /**
     * The meta object literal for the '<em><b>Source Column</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXTRACT__SOURCE_COLUMN = eINSTANCE.getExtract_SourceColumn();

    /**
     * The meta object literal for the '<em><b>Selector</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXTRACT__SELECTOR = eINSTANCE.getExtract_Selector();

    /**
     * The meta object literal for the '<em><b>Comparator</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference EXTRACT__COMPARATOR = eINSTANCE.getExtract_Comparator();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.SelectorImpl <em>Selector</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.SelectorImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getSelector()
     * @generated
     */
    EClass SELECTOR = eINSTANCE.getSelector();

    /**
     * The meta object literal for the '<em><b>N</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECTOR__N = eINSTANCE.getSelector_N();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.ComparatorImpl <em>Comparator</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.ComparatorImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getComparator()
     * @generated
     */
    EClass COMPARATOR = eINSTANCE.getComparator();

    /**
     * The meta object literal for the '<em><b>Keys</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference COMPARATOR__KEYS = eINSTANCE.getComparator_Keys();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.SquashRowsImpl <em>Squash Rows</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.SquashRowsImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getSquashRows()
     * @generated
     */
    EClass SQUASH_ROWS = eINSTANCE.getSquashRows();

    /**
     * The meta object literal for the '<em><b>Columns</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference SQUASH_ROWS__COLUMNS = eINSTANCE.getSquashRows_Columns();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.FilterImpl <em>Filter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.FilterImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getFilter()
     * @generated
     */
    EClass FILTER = eINSTANCE.getFilter();

    /**
     * The meta object literal for the '<em><b>Denylist</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FILTER__DENYLIST = eINSTANCE.getFilter_Denylist();

    /**
     * The meta object literal for the '<em><b>Exceptlist</b></em>' containment reference feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FILTER__EXCEPTLIST = eINSTANCE.getFilter_Exceptlist();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.FilterDenylistImpl <em>Filter Denylist</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.FilterDenylistImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getFilterDenylist()
     * @generated
     */
    EClass FILTER_DENYLIST = eINSTANCE.getFilterDenylist();

    /**
     * The meta object literal for the '<em><b>Denylist</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FILTER_DENYLIST__DENYLIST = eINSTANCE.getFilterDenylist_Denylist();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.FilterExceptlistImpl <em>Filter Exceptlist</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.FilterExceptlistImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getFilterExceptlist()
     * @generated
     */
    EClass FILTER_EXCEPTLIST = eINSTANCE.getFilterExceptlist();

    /**
     * The meta object literal for the '<em><b>Exceptlist</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FILTER_EXCEPTLIST__EXCEPTLIST = eINSTANCE.getFilterExceptlist_Exceptlist();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.FilterRuleImpl <em>Filter Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.FilterRuleImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getFilterRule()
     * @generated
     */
    EClass FILTER_RULE = eINSTANCE.getFilterRule();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.FilterColumnRuleImpl <em>Filter Column Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.FilterColumnRuleImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getFilterColumnRule()
     * @generated
     */
    EClass FILTER_COLUMN_RULE = eINSTANCE.getFilterColumnRule();

    /**
     * The meta object literal for the '<em><b>Column Patterns</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference FILTER_COLUMN_RULE__COLUMN_PATTERNS = eINSTANCE.getFilterColumnRule_ColumnPatterns();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.FilterObjectTypeRuleImpl <em>Filter Object Type Rule</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.FilterObjectTypeRuleImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getFilterObjectTypeRule()
     * @generated
     */
    EClass FILTER_OBJECT_TYPE_RULE = eINSTANCE.getFilterObjectTypeRule();

    /**
     * The meta object literal for the '<em><b>Object Classes</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FILTER_OBJECT_TYPE_RULE__OBJECT_CLASSES = eINSTANCE.getFilterObjectTypeRule_ObjectClasses();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.ColumnNameImpl <em>Column Name</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.ColumnNameImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getColumnName()
     * @generated
     */
    EClass COLUMN_NAME = eINSTANCE.getColumnName();

    /**
     * The meta object literal for the '<em><b>Column Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute COLUMN_NAME__COLUMN_NAME = eINSTANCE.getColumnName_ColumnName();

  }

} //TableDSLPackage
