/**
 * generated by Xtext 2.32.0
 */
package org.feup.els5.dsl.tableDSL;

import org.eclipse.emf.ecore.EAttribute;
import org.eclipse.emf.ecore.EClass;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.emf.ecore.EReference;

/**
 * <!-- begin-user-doc -->
 * The <b>Package</b> for the model.
 * It contains accessors for the meta objects to represent
 * <ul>
 *   <li>each class,</li>
 *   <li>each feature of each class,</li>
 *   <li>each enum,</li>
 *   <li>and each data type</li>
 * </ul>
 * <!-- end-user-doc -->
 * @see org.feup.els5.dsl.tableDSL.TableDSLFactory
 * @model kind="package"
 * @generated
 */
public interface TableDSLPackage extends EPackage
{
  /**
   * The package name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNAME = "tableDSL";

  /**
   * The package namespace URI.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_URI = "http://www.feup.org/els5/dsl/TableDSL";

  /**
   * The package namespace name.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  String eNS_PREFIX = "tableDSL";

  /**
   * The singleton instance of the package.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   */
  TableDSLPackage eINSTANCE = org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl.init();

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.StartImpl <em>Start</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.StartImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getStart()
   * @generated
   */
  int START = 0;

  /**
   * The feature id for the '<em><b>Actions</b></em>' containment reference list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int START__ACTIONS = 0;

  /**
   * The number of structural features of the '<em>Start</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int START_FEATURE_COUNT = 1;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.CreateTableImpl <em>Create Table</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.CreateTableImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getCreateTable()
   * @generated
   */
  int CREATE_TABLE = 1;

  /**
   * The number of structural features of the '<em>Create Table</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int CREATE_TABLE_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.TableActionImpl <em>Table Action</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.TableActionImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getTableAction()
   * @generated
   */
  int TABLE_ACTION = 2;

  /**
   * The number of structural features of the '<em>Table Action</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_ACTION_FEATURE_COUNT = 0;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.LoadDataImpl <em>Load Data</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.LoadDataImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getLoadData()
   * @generated
   */
  int LOAD_DATA = 3;

  /**
   * The number of structural features of the '<em>Load Data</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int LOAD_DATA_FEATURE_COUNT = TABLE_ACTION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.TableInputPathImpl <em>Table Input Path</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.TableInputPathImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getTableInputPath()
   * @generated
   */
  int TABLE_INPUT_PATH = 4;

  /**
   * The feature id for the '<em><b>Path Patterns</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_INPUT_PATH__PATH_PATTERNS = CREATE_TABLE_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Table Input Path</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int TABLE_INPUT_PATH_FEATURE_COUNT = CREATE_TABLE_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.OutputImpl <em>Output</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.OutputImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getOutput()
   * @generated
   */
  int OUTPUT = 5;

  /**
   * The feature id for the '<em><b>Output Paths</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT__OUTPUT_PATHS = TABLE_ACTION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Output</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OUTPUT_FEATURE_COUNT = TABLE_ACTION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.OperationImpl <em>Operation</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.OperationImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getOperation()
   * @generated
   */
  int OPERATION = 6;

  /**
   * The number of structural features of the '<em>Operation</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int OPERATION_FEATURE_COUNT = TABLE_ACTION_FEATURE_COUNT + 0;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.SelectImpl <em>Select</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.SelectImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getSelect()
   * @generated
   */
  int SELECT = 7;

  /**
   * The feature id for the '<em><b>Columns Patterns</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT__COLUMNS_PATTERNS = OPERATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>Column Patterns</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT__COLUMN_PATTERNS = OPERATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Select</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SELECT_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.RenameColumnImpl <em>Rename Column</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.RenameColumnImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getRenameColumn()
   * @generated
   */
  int RENAME_COLUMN = 8;

  /**
   * The feature id for the '<em><b>Old Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RENAME_COLUMN__OLD_NAME = OPERATION_FEATURE_COUNT + 0;

  /**
   * The feature id for the '<em><b>New Name</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RENAME_COLUMN__NEW_NAME = OPERATION_FEATURE_COUNT + 1;

  /**
   * The number of structural features of the '<em>Rename Column</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int RENAME_COLUMN_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 2;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.ExtractImpl <em>Extract</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.ExtractImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getExtract()
   * @generated
   */
  int EXTRACT = 9;

  /**
   * The feature id for the '<em><b>Placeholder</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTRACT__PLACEHOLDER = OPERATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Extract</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int EXTRACT_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.SquashRowsImpl <em>Squash Rows</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.SquashRowsImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getSquashRows()
   * @generated
   */
  int SQUASH_ROWS = 10;

  /**
   * The feature id for the '<em><b>Columns</b></em>' attribute list.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SQUASH_ROWS__COLUMNS = OPERATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Squash Rows</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int SQUASH_ROWS_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 1;

  /**
   * The meta object id for the '{@link org.feup.els5.dsl.tableDSL.impl.FilterImpl <em>Filter</em>}' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @see org.feup.els5.dsl.tableDSL.impl.FilterImpl
   * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getFilter()
   * @generated
   */
  int FILTER = 11;

  /**
   * The feature id for the '<em><b>Placeholder</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER__PLACEHOLDER = OPERATION_FEATURE_COUNT + 0;

  /**
   * The number of structural features of the '<em>Filter</em>' class.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @generated
   * @ordered
   */
  int FILTER_FEATURE_COUNT = OPERATION_FEATURE_COUNT + 1;


  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.Start <em>Start</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Start</em>'.
   * @see org.feup.els5.dsl.tableDSL.Start
   * @generated
   */
  EClass getStart();

  /**
   * Returns the meta object for the containment reference list '{@link org.feup.els5.dsl.tableDSL.Start#getActions <em>Actions</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the containment reference list '<em>Actions</em>'.
   * @see org.feup.els5.dsl.tableDSL.Start#getActions()
   * @see #getStart()
   * @generated
   */
  EReference getStart_Actions();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.CreateTable <em>Create Table</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Create Table</em>'.
   * @see org.feup.els5.dsl.tableDSL.CreateTable
   * @generated
   */
  EClass getCreateTable();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.TableAction <em>Table Action</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Table Action</em>'.
   * @see org.feup.els5.dsl.tableDSL.TableAction
   * @generated
   */
  EClass getTableAction();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.LoadData <em>Load Data</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Load Data</em>'.
   * @see org.feup.els5.dsl.tableDSL.LoadData
   * @generated
   */
  EClass getLoadData();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.TableInputPath <em>Table Input Path</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Table Input Path</em>'.
   * @see org.feup.els5.dsl.tableDSL.TableInputPath
   * @generated
   */
  EClass getTableInputPath();

  /**
   * Returns the meta object for the attribute list '{@link org.feup.els5.dsl.tableDSL.TableInputPath#getPathPatterns <em>Path Patterns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Path Patterns</em>'.
   * @see org.feup.els5.dsl.tableDSL.TableInputPath#getPathPatterns()
   * @see #getTableInputPath()
   * @generated
   */
  EAttribute getTableInputPath_PathPatterns();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.Output <em>Output</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Output</em>'.
   * @see org.feup.els5.dsl.tableDSL.Output
   * @generated
   */
  EClass getOutput();

  /**
   * Returns the meta object for the attribute list '{@link org.feup.els5.dsl.tableDSL.Output#getOutputPaths <em>Output Paths</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Output Paths</em>'.
   * @see org.feup.els5.dsl.tableDSL.Output#getOutputPaths()
   * @see #getOutput()
   * @generated
   */
  EAttribute getOutput_OutputPaths();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.Operation <em>Operation</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Operation</em>'.
   * @see org.feup.els5.dsl.tableDSL.Operation
   * @generated
   */
  EClass getOperation();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.Select <em>Select</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Select</em>'.
   * @see org.feup.els5.dsl.tableDSL.Select
   * @generated
   */
  EClass getSelect();

  /**
   * Returns the meta object for the attribute list '{@link org.feup.els5.dsl.tableDSL.Select#getColumnsPatterns <em>Columns Patterns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Columns Patterns</em>'.
   * @see org.feup.els5.dsl.tableDSL.Select#getColumnsPatterns()
   * @see #getSelect()
   * @generated
   */
  EAttribute getSelect_ColumnsPatterns();

  /**
   * Returns the meta object for the attribute list '{@link org.feup.els5.dsl.tableDSL.Select#getColumnPatterns <em>Column Patterns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Column Patterns</em>'.
   * @see org.feup.els5.dsl.tableDSL.Select#getColumnPatterns()
   * @see #getSelect()
   * @generated
   */
  EAttribute getSelect_ColumnPatterns();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.RenameColumn <em>Rename Column</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Rename Column</em>'.
   * @see org.feup.els5.dsl.tableDSL.RenameColumn
   * @generated
   */
  EClass getRenameColumn();

  /**
   * Returns the meta object for the attribute '{@link org.feup.els5.dsl.tableDSL.RenameColumn#getOldName <em>Old Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Old Name</em>'.
   * @see org.feup.els5.dsl.tableDSL.RenameColumn#getOldName()
   * @see #getRenameColumn()
   * @generated
   */
  EAttribute getRenameColumn_OldName();

  /**
   * Returns the meta object for the attribute '{@link org.feup.els5.dsl.tableDSL.RenameColumn#getNewName <em>New Name</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>New Name</em>'.
   * @see org.feup.els5.dsl.tableDSL.RenameColumn#getNewName()
   * @see #getRenameColumn()
   * @generated
   */
  EAttribute getRenameColumn_NewName();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.Extract <em>Extract</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Extract</em>'.
   * @see org.feup.els5.dsl.tableDSL.Extract
   * @generated
   */
  EClass getExtract();

  /**
   * Returns the meta object for the attribute '{@link org.feup.els5.dsl.tableDSL.Extract#getPlaceholder <em>Placeholder</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Placeholder</em>'.
   * @see org.feup.els5.dsl.tableDSL.Extract#getPlaceholder()
   * @see #getExtract()
   * @generated
   */
  EAttribute getExtract_Placeholder();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.SquashRows <em>Squash Rows</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Squash Rows</em>'.
   * @see org.feup.els5.dsl.tableDSL.SquashRows
   * @generated
   */
  EClass getSquashRows();

  /**
   * Returns the meta object for the attribute list '{@link org.feup.els5.dsl.tableDSL.SquashRows#getColumns <em>Columns</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute list '<em>Columns</em>'.
   * @see org.feup.els5.dsl.tableDSL.SquashRows#getColumns()
   * @see #getSquashRows()
   * @generated
   */
  EAttribute getSquashRows_Columns();

  /**
   * Returns the meta object for class '{@link org.feup.els5.dsl.tableDSL.Filter <em>Filter</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for class '<em>Filter</em>'.
   * @see org.feup.els5.dsl.tableDSL.Filter
   * @generated
   */
  EClass getFilter();

  /**
   * Returns the meta object for the attribute '{@link org.feup.els5.dsl.tableDSL.Filter#getPlaceholder <em>Placeholder</em>}'.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the meta object for the attribute '<em>Placeholder</em>'.
   * @see org.feup.els5.dsl.tableDSL.Filter#getPlaceholder()
   * @see #getFilter()
   * @generated
   */
  EAttribute getFilter_Placeholder();

  /**
   * Returns the factory that creates the instances of the model.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the factory that creates the instances of the model.
   * @generated
   */
  TableDSLFactory getTableDSLFactory();

  /**
   * <!-- begin-user-doc -->
   * Defines literals for the meta objects that represent
   * <ul>
   *   <li>each class,</li>
   *   <li>each feature of each class,</li>
   *   <li>each enum,</li>
   *   <li>and each data type</li>
   * </ul>
   * <!-- end-user-doc -->
   * @generated
   */
  interface Literals
  {
    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.StartImpl <em>Start</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.StartImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getStart()
     * @generated
     */
    EClass START = eINSTANCE.getStart();

    /**
     * The meta object literal for the '<em><b>Actions</b></em>' containment reference list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EReference START__ACTIONS = eINSTANCE.getStart_Actions();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.CreateTableImpl <em>Create Table</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.CreateTableImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getCreateTable()
     * @generated
     */
    EClass CREATE_TABLE = eINSTANCE.getCreateTable();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.TableActionImpl <em>Table Action</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.TableActionImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getTableAction()
     * @generated
     */
    EClass TABLE_ACTION = eINSTANCE.getTableAction();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.LoadDataImpl <em>Load Data</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.LoadDataImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getLoadData()
     * @generated
     */
    EClass LOAD_DATA = eINSTANCE.getLoadData();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.TableInputPathImpl <em>Table Input Path</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.TableInputPathImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getTableInputPath()
     * @generated
     */
    EClass TABLE_INPUT_PATH = eINSTANCE.getTableInputPath();

    /**
     * The meta object literal for the '<em><b>Path Patterns</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute TABLE_INPUT_PATH__PATH_PATTERNS = eINSTANCE.getTableInputPath_PathPatterns();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.OutputImpl <em>Output</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.OutputImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getOutput()
     * @generated
     */
    EClass OUTPUT = eINSTANCE.getOutput();

    /**
     * The meta object literal for the '<em><b>Output Paths</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute OUTPUT__OUTPUT_PATHS = eINSTANCE.getOutput_OutputPaths();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.OperationImpl <em>Operation</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.OperationImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getOperation()
     * @generated
     */
    EClass OPERATION = eINSTANCE.getOperation();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.SelectImpl <em>Select</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.SelectImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getSelect()
     * @generated
     */
    EClass SELECT = eINSTANCE.getSelect();

    /**
     * The meta object literal for the '<em><b>Columns Patterns</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECT__COLUMNS_PATTERNS = eINSTANCE.getSelect_ColumnsPatterns();

    /**
     * The meta object literal for the '<em><b>Column Patterns</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SELECT__COLUMN_PATTERNS = eINSTANCE.getSelect_ColumnPatterns();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.RenameColumnImpl <em>Rename Column</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.RenameColumnImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getRenameColumn()
     * @generated
     */
    EClass RENAME_COLUMN = eINSTANCE.getRenameColumn();

    /**
     * The meta object literal for the '<em><b>Old Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RENAME_COLUMN__OLD_NAME = eINSTANCE.getRenameColumn_OldName();

    /**
     * The meta object literal for the '<em><b>New Name</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute RENAME_COLUMN__NEW_NAME = eINSTANCE.getRenameColumn_NewName();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.ExtractImpl <em>Extract</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.ExtractImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getExtract()
     * @generated
     */
    EClass EXTRACT = eINSTANCE.getExtract();

    /**
     * The meta object literal for the '<em><b>Placeholder</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute EXTRACT__PLACEHOLDER = eINSTANCE.getExtract_Placeholder();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.SquashRowsImpl <em>Squash Rows</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.SquashRowsImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getSquashRows()
     * @generated
     */
    EClass SQUASH_ROWS = eINSTANCE.getSquashRows();

    /**
     * The meta object literal for the '<em><b>Columns</b></em>' attribute list feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute SQUASH_ROWS__COLUMNS = eINSTANCE.getSquashRows_Columns();

    /**
     * The meta object literal for the '{@link org.feup.els5.dsl.tableDSL.impl.FilterImpl <em>Filter</em>}' class.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @see org.feup.els5.dsl.tableDSL.impl.FilterImpl
     * @see org.feup.els5.dsl.tableDSL.impl.TableDSLPackageImpl#getFilter()
     * @generated
     */
    EClass FILTER = eINSTANCE.getFilter();

    /**
     * The meta object literal for the '<em><b>Placeholder</b></em>' attribute feature.
     * <!-- begin-user-doc -->
     * <!-- end-user-doc -->
     * @generated
     */
    EAttribute FILTER__PLACEHOLDER = eINSTANCE.getFilter_Placeholder();

  }

} //TableDSLPackage
