/**
 * generated by Xtext 2.32.0
 */
package org.feup.els5.dsl.tableDSL;


/**
 * <!-- begin-user-doc -->
 * A representation of the model object '<em><b>Top NSelector</b></em>'.
 * <!-- end-user-doc -->
 *
 * <p>
 * The following features are supported:
 * </p>
 * <ul>
 *   <li>{@link org.feup.els5.dsl.tableDSL.TopNSelector#getN <em>N</em>}</li>
 * </ul>
 *
 * @see org.feup.els5.dsl.tableDSL.TableDSLPackage#getTopNSelector()
 * @model
 * @generated
 */
public interface TopNSelector extends Selector
{
  /**
   * Returns the value of the '<em><b>N</b></em>' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @return the value of the '<em>N</em>' attribute.
   * @see #setN(int)
   * @see org.feup.els5.dsl.tableDSL.TableDSLPackage#getTopNSelector_N()
   * @model
   * @generated
   */
  int getN();

  /**
   * Sets the value of the '{@link org.feup.els5.dsl.tableDSL.TopNSelector#getN <em>N</em>}' attribute.
   * <!-- begin-user-doc -->
   * <!-- end-user-doc -->
   * @param value the new value of the '<em>N</em>' attribute.
   * @see #getN()
   * @generated
   */
  void setN(int value);

} // TopNSelector
